server:
  port: 8765
eureka:
  client:
    service-url:
      #eureka server集群配置
      #defaultZone: http://peer1:8761/eureka/
      #eureka server集群配置
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    hostname: peer1
    prefer-ip-address: true
spring:
  application:
    name: eureka-client